disqus:
  enable: false 
  shortname: 
  api: 
  apikey: 
  admin: 
  admin_label: 
uyan: 
livere: 
changyan: 
changyan_conf: 
gitalk: 
  enable: true 
  owner: wanger-sjtu 
  repo: wanger-sjtu.github.io 
  client_id: "25c52264eb62b88a09d0" 
  client_secret: "08dd790dcadb5826a40004b55e56414d2f477734" 
  admin: wanger-sjtu 
  createIssueManually: false 
valine: 
  enable: false 
  appid: 
  appkey: 
  notify: false 
  verify: false 
  placeholder: Just so so 
  avatar: "mm" 
  pageSize: 10 
  guest_info: nick,mail,link 
minivaline: 
  enable: false 
  appId: 
  appKey: 
  placeholder: Write a Comment 
  adminEmailMd5: 
  math: true 
  md: true 
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:
waline: 
  enable: false 
  serverURL: 
  pageSize: 
utterances: 
  enable: false 
  repo: 
  identifier: title 
  theme: github-light 
twikoo: 
  enable: false 
  envId: 
  region: 
  path: 

google_search: true 
baidu_search: false 
swiftype: 
self_search: false 
google_analytics: "G-D0GZY9PECP"
baidu_analytics: 
fancybox: true 
show_category_count: false 
toc_number: true 
shareto: false 
busuanzi: true 
wordcount: false 
widgets_on_small_screens: false 
canvas_nest:
  enable: false 
  color: 
  opacity: 
  zIndex: 
  count: 
donate:
  enable: false 
  github: 
  alipay_qr: 
  wechat_qr: 
  btc_qr: 
  btc_key: 
  paypal_url: 
post_copyright:
  enable: true 
  author: 王二
  copyright_text: "本博客所有文章除特别声明外，均采用 BY-NC-SA 许可协议。转载请注明出处！"
love: false 
plantuml: 
  render: "PlantUMLServer" 
  outputFormat: "svg" 
copycode: true 
dark: false 
totop: true 
external_css: false 


menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: tags
    directory: tags
    icon: fa-tag
  - page: about
    directory: about/
    icon: fa-user
      #- page: category
      #    directory: categories
      #    icon: fa-category

info:
  avatar: /img/avatar.jpg
  discription: 除了这只猪，还没见过谁敢于如此无视对生活的设置。
  outlinkitem:
    - name: github
      outlink: https://github.com/Wanger-SJTU
      message: Github
    - name: rss
      outlink: /atom.xml
      message: RSS

widgets: 
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  # - links

# links:
#   - title: site-name1
#     url: http://www.example1.com/
#   - title: site-name2
#     url: http://www.example2.com/
#   - title: site-name3
#     url: http://www.example3.com/

# timeline:
#   - num: 1
#     word: 2014/06/12-Start
#   - num: 2
#     word: 2014/11/29-XXX
#   - num: 3
#     word: 2015/02/18-DDD
#   - num: 4
#     word: More

# Static files
js: js
css: css

# Theme version
version: 1.0.0
